First pull request.
Anton-Lyn/test pull request #2
Opened 2021-06-03 11:33 UTC by Anton-Lyn

- Added display of all items to the client
- Added first filter authorization.

Only from branch "Test1" to branch "master". I don't know why...

2021-06-03 18:03 UTC, edvardino requested changes

2021-06-03 18:03 UTC, edvardino commented on src/main/java/com/ClassForTestMethod.java
> +public class ClassForTestMethod {
для чего этот класс?

2021-06-03 18:03 UTC, edvardino commented on src/main/java/com/entity/Subject.java
> +    String created_At;
если такое увидят тебя даже грузчиком в епам не возьмут. Конвеншены не по приколу были  написаны

2021-06-03 18:03 UTC, edvardino commented on src/main/java/com/filter/Filter.java
> +        if (user == null && !(uri.endsWith("index.jsp") || uri.endsWith("loginError.jsp")) && s == null){
очень сложная логика в одной строке... Сложно понять что тут происходит, но якобы если я в параметре укажу любой свой имейл - то я окажусь авторизированным пользователем???

2021-06-03 18:03 UTC, edvardino commented on src/main/java/com/service/SubjectService.java
> +    Object getSubjectList();
У тебя никакой код не должен возвращать обжект

2021-06-03 18:03 UTC, edvardino commented on src/main/java/com/service/serviceImpl/SubjectServiceImpl.java
> +        SubjectDAOImpl subjectDAO = new SubjectDAOImpl();
дао, сервис, фасад - неважно - все это создается в одном экземпляре и хранится на уровне переменных класса. Но никак не создание дао в методе

2021-06-04 07:47 UTC, Anton-Lyn commented on src/main/java/com/ClassForTestMethod.java
> +public class ClassForTestMethod {
Его потом удалю, в нем некоторые методы тестирую

2021-06-04 15:37 UTC, Anton-Lyn commented on src/main/java/com/entity/Subject.java
> +    String created_At;
Исправил

2021-06-04 15:37 UTC, Anton-Lyn commented on src/main/java/com/filter/Filter.java
> +        if (user == null && !(uri.endsWith("index.jsp") || uri.endsWith("loginError.jsp")) && s == null){
Ну тут самый норм варик
Исправил. Теперь регистрация работает

2021-06-04 15:40 UTC, Anton-Lyn commented on src/main/java/com/service/SubjectService.java
> +    Object getSubjectList();
Исправил

2021-06-04 15:47 UTC, Anton-Lyn commented on src/main/java/com/service/serviceImpl/SubjectServiceImpl.java
> +        SubjectDAOImpl subjectDAO = new SubjectDAOImpl();
Исправил

2021-06-04 15:50 UTC, edvardino commented on src/main/java/com/entity/Subject.java
> +    String created_At;
Не вижу

2021-06-04 15:51 UTC, edvardino commented on src/main/java/com/filter/Filter.java
> +        if (user == null && !(uri.endsWith("index.jsp") || uri.endsWith("loginError.jsp")) && s == null){
Хозяин барин, тоже не вижу изменений

2021-06-04 15:51 UTC, edvardino commented on src/main/java/com/service/SubjectService.java
> +    Object getSubjectList();
Нет изменений, все по прежнему

2021-06-04 15:51 UTC, edvardino commented on src/main/java/com/service/serviceImpl/SubjectServiceImpl.java
> +        SubjectDAOImpl subjectDAO = new SubjectDAOImpl();
Идентично

2021-06-04 16:10 UTC, edvardino requested changes

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/DAO/DAOImpl/SubjectDAOImpl.java
> +    private static SubjectDAOImpl subjectDAO;
статики у тебя быть не должно, по хорошему. если хочешь оставить - готовься к вопросам: а нахуй ты это написал и тому подобных

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/DAO/DAOImpl/UserDAOImpl.java
> +            log.info("Try to connection to DB to find User");
первый раз пропустил, но второй не удержался: глаза режет.
https://translate.google.com/?sl=en&tl=ru&text=connection&op=translate
заходим, изучаем

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/controller/UserLoginController.java
>          session.setAttribute("update", receivedUser.getUpdateAT());
не согласованные две переменные, так дела не делаются

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/entity/Subject.java
> +    String createdData;
та же проблема что и у ярика, тоже глаз режет. заходим на translate.google.com и смотрим различие двух слов: data и date. и больше такого не пишем никогда

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/filter/Filter.java
> +public class Filter implements javax.servlet.Filter {
такого быть тоже не должно, назови класс по нормальному, и для имплементации изпользуй импорт

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/service/SubjectService.java
> +    Object getSubjectList();
тут все по прежнему...

2021-06-04 16:10 UTC, edvardino commented on src/main/java/com/service/serviceImpl/SubjectServiceImpl.java
> +        return SubjectDAOImpl.getInstance().getAllSubjects();
еще раз пишу, у тебя должен храниться инстанс дао на уровне филда класса

2021-06-07 08:06 UTC, edvardino approved these changes

2021-06-07 08:06 UTC, merged